### PR TITLE
Generate pricefile using simple visitor pattern

### PR DESCRIPTION
**Pull request by mattias-p**
No functional changes. Everything about business data extraction is centralized into the abstract base class, allowing the integration classes to focus entirely on generating output.

### CODE REVIEW

**Comment by pelmered** [comment]
I like the idea of having the integration classes super slim like this, but I think I would prefer to call getters from the integration class rather than generating the same array for all integrations in the generator class, like this:

echo $this::format_value($this->get_category());
echo $this::format_value($this->get_product_sku());
echo $this::format_value($this->get_price());
...

What do you think?

**Comment by mattias-p** [comment]
Not a bad idea at all, although it does bring some complexity since you need to pass around some additional state. It also involves more work than I'm able to fit into my day unless you're willing to wait for it. However, I'll jot down an outline here for whoever digs in first:
 1. Write getters for the remaining properties.
 2. Pack up $product, $product_data, $product_meta and possibly $product_id in an array and have all the getters take the entire wrapped up array as their single argument - no matter which one of its values it needs.
 3. Modify product() to accept an opaque value that it just passes along to the getters (instead of reading the business data directly from $product_info array), and send the wrapped up array as the only argument to product() (instead of sending the product info array).

I also thought about using a product representation class with methods for all the getters, but I'm not sure all the getters can be moved without complications.

**Comment by optimalnorge** [comment]
Or you can set $product and $product_meta($product_data is only a subset of $product for convenience  and is not really needed) as class variables in the base class and then fetch from there in getters. Thoughts?

**Comment by mattias-p** [comment]
I think that's a bad idea. The more shared variables you have that are assigned outside of the constructor, the harder it is to follow the flow of data through the code.

**Comment by pelmered** [comment]
That was me in the previous comment. Wrong account...

Yes, that is true even if it's quite obvious what data the variables contain. 

Maybe it's better to make a product class after all. A class that you pass a product id to and that gets the data in the constructor and then is used through getters. Like this:

Generator loop
```php
$this->product(new WC_Pricefiles_Product( get_the_id() ));
```
product()
```php
echo $this::format_value($product->get_category());
echo $this::format_value($product->get_product_sku());
echo $this::format_value($product->get_price());
```

That makes also very readable code.

**Comment by mattias-p** [comment]
I agree that it's obvious what the variables contain when generate_pricefile() is calling product(), but I don't think it's obvious that the variables are meaningless and shouldn't be used in other contexts. Of course you could fix that with comments at the member variable declarations.

The OO solution is much easier to read, but it's also a little more work to write.

I found some time to implement the steps I outlined above. If you like the OO solution the remaining steps are:
 1. Make get_price() and get_shipping_cost() methods static.
 2. Create a product class with private members $product and $product_meta.
 3. Move all getters (and whatever supporting code resulted from step 1) into the new product class.
 4. Modify Generator->generate_pricefile() and *->product() to use product objects instead of "opaque" arrays.

I'm not familiar with the price and shipping cost calculation code, and I'm not very eager to learn it either, so I won't be touching that. I suggest you take the ball from here. This far I've been having fun.

**Comment by pelmered** [comment]
A lot of good improvements there and I agree on those steps. I started with he product class on Friday to and I will probably be able to finish it today or tomorrow. 

__What is the purpose of making the getters static?__

Yes, the shipping calculation is a bit complex, but that is the only way to calculate the shipping correctly. You have to build up a package object(cart + destination address) that you pass to the shipping calculation function(calculate_shipping_for_package()). 

I'll merge this now and continue with those steos.

**Comment by mattias-p** [comment]
I'm glad you like it!

The purpose of making the getters static in the generator class (including any other members that are to be moved) is just to make them truly independent of the generator instance. Surely you can do that without adding keywords that you most likely want to remove again, but in cases where I can use the compiler instead of my own brain, I tend to opt for the former.

**Comment by pelmered** [comment]
I've now completed those steps and got everything to work again. 

The things that's left to do before release of next version is:
- Refactor and improve cache
- Support for product variations (I have contacted Prisjakt about how this should be formatted in the pricefile, but no response yet).

**Pull request merged**
